#!/bin/bash

files=( * )

# iterate over them
for file in "${files[@]}"; do
    echo "$file"
done
#!/bin/bash

deploy=false
uglify=false

while (( $# > 1 )); do case $1 in
    --deploy) deploy="$2";;
    --uglify) uglify="$2";;
    *) break;
  esac; shift 2
done

$deploy && echo "will deploy... deploy = $deploy"
$uglify && echo "will uglify... uglify = $uglify"
#!/usr/bin/env bash
echo "Who are you?"
read name
echo "Hello, $name."
